08_People/Models/Entity/City.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace _08_People.Models.Entity
{
    public class City
    {
        [Key]
        public int Id { get; set; }

        public string CityName { get; set; }




        //  Navigational properties
        [ForeignKey("Country")]
        public int CountryId { get; set; }

        public Country Country { get; set; }

        public List<Person> People { get; set; }

        
        public City()
        {
            this.People = new List<Person>();
        }
        public City(string cityName)
        {
            CityName = cityName;
        }


    }
}

08_People/Models/Repos/Cities/DatabaseCitiesRepo.cs
using _08_People.Data;
using _08_People.Models.Entity;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace _08_People.Models.Repos
{
    public class DatabaseCitiesRepo : ICitiesRepo
    {
        private readonly PeopleDbContext _peopleDbContext;

        public DatabaseCitiesRepo(PeopleDbContext peopleDbContext)
        {
            _peopleDbContext = peopleDbContext;
        }




        public City Create(City city)
        {
            _peopleDbContext.Cities.Add(city);
            _peopleDbContext.SaveChanges();
            return city;
        }

        public List<City> Read()
        {
            return _peopleDbContext.Cities.ToList();
        }

        public City Read(int id)
        {
            return _peopleDbContext.Cities.Include(p => p.People).SingleOrDefault(c => c.Id == id);
        }

        public bool Update(City city)
        {
            _peopleDbContext.Cities.Update(city);
            _peopleDbContext.SaveChanges();
            return true;
        }

        public bool Delete(City city)
        {
            _peopleDbContext.Cities.Remove(city);
            _peopleDbContext.SaveChanges();
            return true;
        }
    }
}

08_People/Models/Repos/Cities/ICitiesRepo.cs
using _08_People.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace _08_People.Models.Repos
{
    public interface ICitiesRepo
    {
        //C
        City Create(City city);

        //R
        List<City> Read();
        City Read(int id);

        //U
        bool Update(City city);

        //D
        bool Delete(City city);
    }
}

08_People/Models/Services/Cities/CitiesService.cs
using _08_People.Models.Entity;
using _08_People.Models.Repos;
using _08_People.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace _08_People.Models.Services
{
    public class CitiesService : ICitiesService
    {
        private readonly ICitiesRepo _citiesRepo;
        public CitiesService(ICitiesRepo citiesRepo)
        {
            _citiesRepo = citiesRepo;
        }


        public City Add(CreateCityViewModel newCity)
        {
            if(newCity == null)
            {
                return null;
            }
            else
            {
                City city = new City()
                {
                    CityName = newCity.CityName,
                    CountryId = newCity.CountryId
                };

                return _citiesRepo.Create(city);
            }
        }

        public List<City> All()
        {
            return _citiesRepo.Read();
            //throw new NotImplementedException();
        }

        public City FindById(int id)
        {
            return _citiesRepo.Read(id);
        }

        public List<City> Search(string search)
        {
            if (string.IsNullOrEmpty(search))
            {
                return All();
            }
            else
            {
                List<City> result = All().Where(x => x.CityName.ToLower().Contains(search.ToLower())).ToList();
                if(result.Count < 1)
                {
                    return All();
                }
                else
                {
                    return result;
                }
            }
        }

        public bool Edit(int id, CreateCityViewModel eCity)
        {
            City city = FindById(id);

            if(city != null)
            {
                city.CityName = eCity.CityName;
                city.CountryId = eCity.CountryId;
                return _citiesRepo.Update(city);
            }
            return false;
        }

        public bool Remove(int id)
        {
            City city = FindById(id);

            if(city != null)
            {
                return _citiesRepo.Delete(city);
            }
            return false;
        }
    }
}

08_People/Models/Services/Cities/ICitiesService.cs
using _08_People.Models.Entity;
using _08_People.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace _08_People.Models.Services
{
    public interface ICitiesService
    {
        City Add(CreateCityViewModel city);
        List<City> All();
        List<City> Search(string search);
        City FindById(int id);
        bool Edit(int id, CreateCityViewModel city);
        bool Remove(int id);
    }
}

08_People/Models/ViewModels/Cities/CitiesViewModel.cs
using _08_People.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace _08_People.Models.ViewModels
{
    public class CitiesViewModel
    {
        public string CityName { get; set; }

        public List<City> Cities { get; set; }
        public Country Country { get; set; }
        public CitiesViewModel() { }
    }
}

08_People/Models/ViewModels/Cities/CreateCityViewModel.cs
using _08_People.Models.Entity;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace _08_People.Models.ViewModels
{
    public class CreateCityViewModel
    {
        [Required]
        [StringLength(50, MinimumLength = 2)]
        public string CityName { get; set; }

        [Required]
        [DisplayName("Country")]
        public int CountryId { get; set; }
        public List<Country> CountryList { get; set; } 
    }
}

08_People/Controllers/CitiesController.cs
using _08_People.Models.Entity;
using _08_People.Models.Services;
using _08_People.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace _08_People.Controllers
{
    public class CitiesController : Controller
    {
        private readonly ICitiesService _citiesService;
        private readonly ICountriesService _countriesService;
        public CitiesController(ICitiesService citiesService, ICountriesService countriesService)
        {
            _citiesService = citiesService;
            _countriesService = countriesService;
        }



        [HttpGet]
        public IActionResult Index(string search)
        {
            CitiesViewModel cities = new CitiesViewModel { Cities = _citiesService.Search(search) };
            return View(cities);
        }


        [HttpGet]
        public IActionResult Create()
        {
            CreateCityViewModel city = new CreateCityViewModel();
            city.CountryList = _countriesService.All();
            return View(city);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CreateCityViewModel city)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _citiesService.Add(city);
                }
                catch (ArgumentException exception)
                {
                    ModelState.AddModelError("City & Country", exception.Message);
                    city.CountryList = _countriesService.All();

                    return View(city);
                }
                return RedirectToAction(nameof(Index));
            }

            city.CountryList = _countriesService.All();
            return RedirectToAction(nameof(Create));
        }

        //[HttpGet]
        //public IActionResult Create(int id)
        //{
        //    CreateCityViewModel city = new CreateCityViewModel();
        //    city.CountryId = id;
        //    return View(city);
        //}

        [HttpGet]
        public ActionResult Details(int id)
        {
            City city = _citiesService.FindById(id);
            if (city == null) { RedirectToAction(nameof(Index)); }
            return View(city);

            //Country country = _countriesService.FindById(id);
            //if (country == null) { RedirectToAction(nameof(Index)); }
            //return View(country);
        }
        public ActionResult Edit(int id)    // Not implemented
        {
            //Person person = _peopleService.FindById(id);
            //if (person == null) { return RedirectToAction(nameof(Index)); }

            //CreatePersonViewModel editPerson = new CreatePersonViewModel()
            //{
            //    //Id = person.Id,   //Add and set Id in CreatePersonViewModel??
            //    FirstName = person.FirstName,
            //    LastName = person.LastName,
            //    PhoneNumber = person.PhoneNumber,
            //    InCity = person.InCity
            //};

            //ViewBag.Id = id;
            //return View(editPerson);
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit()    // Not implemented (int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }




    }
}

08_People/Controllers/PeopleController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _08_People.Models.Entity;
using _08_People.Models.ViewModels;
using _08_People.Models.Services;
using _08_People.Models.Repos;

namespace _08_People.Controllers
{
    public class PeopleController : Controller
    {
        private readonly IPeopleService _peopleService;
        private readonly ICitiesService _citiesService;
        public PeopleController(IPeopleService ipeopleService, ICitiesService citiesService)
        {
            _peopleService = ipeopleService;
            _citiesService = citiesService;
        }



        [HttpGet]
        public ActionResult Index(string search)
        {
            PeopleViewModel people = new PeopleViewModel { Persons = _peopleService.Search(search) };
            return View(people);
        }


        [HttpGet]
        public ActionResult Create()
        {
            CreatePersonViewModel person = new CreatePersonViewModel();
            person.CityList = _citiesService.All();
            return View(person);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreatePersonViewModel person)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _peopleService.Add(person);
                }
                catch (ArgumentException exception)
                {
                    ModelState.AddModelError("Person and City", exception.Message);
                    person.CityList = _citiesService.All();

                    return View(person);
                }
                return RedirectToAction(nameof(Index));     // Redirection to "Details" would be preferred
            }

            person.CityList = _citiesService.All();
            return RedirectToAction(nameof(Create));
        }


        [HttpGet]
        public ActionResult Details(int id)
        {
            Person person = _peopleService.FindById(id);
            if(person == null) { RedirectToAction(nameof(Index)); }
            //add if (person == null) redirect to index, or indicate in details view that person is gone (in case of deletion)
            return View(person);
        }


        public ActionResult Edit(int id)    // Not implemented
        {
            //Person person = _peopleService.FindById(id);
            //if (person == null) { return RedirectToAction(nameof(Index)); }

            //CreatePersonViewModel editPerson = new CreatePersonViewModel()
            //{
            //    //Id = person.Id,   //Add and set Id in CreatePersonViewModel??
            //    FirstName = person.FirstName,
            //    LastName = person.LastName,
            //    PhoneNumber = person.PhoneNumber,
            //    InCity = person.InCity
            //};

            //ViewBag.Id = id;
            //return View(editPerson);
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)    // Not implemented
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }


        public ActionResult Delete()
        {
            //might use for partial view, and load with "Are you sure?" question
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            Person person = _peopleService.FindById(id);
            if (person == null)
            {
                return RedirectToAction(nameof(Index));
            }
            _peopleService.Remove(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

08_People/Views/Cities/Create.cshtml
@model _08_People.Models.ViewModels.CreateCityViewModel
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Add New City</h3>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CityName" class="control-label"></label>
                <input asp-for="CityName" class="form-control" />
                <span asp-validation-for="CityName" class="text-danger"></span>
            </div>


            <div>
                <label asp-for="CountryId"></label>
                <select asp-for="CountryId">
                    @foreach (Country country in Model.CountryList)
                    {
                        <option value="@country.Id">@country.CountryName</option>
                    }
                </select>
                <span asp-validation-for="CountryId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

08_People/Views/Cities/Details.cshtml
@model _08_People.Models.Entity.City
@{
    ViewData["Title"] = "Details";
}

<h3>People in @Model.CityName</h3>
<hr />

<div class="container row">
    <div class="col">
        <a class="nav-link text-dark" asp-area="" asp-controller="People" asp-action="Create">Add Person</a>
    </div>

    <div class="align-items-end">
        @using (Html.BeginForm("Index", "Cities", FormMethod.Get))
        {
            @Html.TextBox("search")
            <input type="submit" value="Search" />
        }
    </div>
</div>



@if (Model.People.Count() < 1)
{
    <br />
    <p>There are no people in this city at the moment</p>
}
else
{



    <br />
    <div class="container">
        <div class="row table-primary" style="border-bottom-style: ridge; font-weight:bolder; font-size:larger">
            <div class="col">First Name</div>
            <div class="col">Last Name</div>
            <div class="col">City</div>
            <div class="col">Details</div>
        </div>


        @foreach (var Person in Model.People)
        {

            <div class="divChecker divHover tableBgColor row">

                <div class="col align-self-center">@Person.FirstName</div>
                <div class="col align-self-center">@Person.LastName</div>
                <div class="col align-self-center">@Person.City.CityName</div>
                <div class="col align-self-center">
                    <a asp-controller="People" asp-action="Details" asp-route-id="@Person.Id">
                        <input type="submit" class="btn btn-info" value="Details" />
                    </a>
                </div>

            </div>
        }





    </div>
}










<div>
    @*<a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |*@
    <a asp-action="Index">Back to List</a>
</div>

08_People/Views/Cities/Index.cshtml
@model _08_People.Models.ViewModels.CitiesViewModel

@{
    ViewData["Title"] = "Cities";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (Model.Cities.Count < 1)
{
    <br />
    <p>There are no cities in the list at the moment</p>
}
else
{
    <h3>Cities</h3>
    <hr />

    <div class="container row">
        <div class="col row">
            <a class="nav-link text-dark" asp-area="" asp-controller="Cities" asp-action="Create">Add City</a>
        </div>

        <div class="align-items-end">
            @using (Html.BeginForm("Index", "Cities", FormMethod.Get))
            {
                @Html.TextBox("search")
                <input type="submit" value="Search" />
            }
        </div>
    </div>


    <br />
    <div class="container">
        <div class="row table-primary" style="border-bottom-style: ridge; font-weight:bolder; font-size:larger">
            <div class="col">City</div>
            <div class="col">Num. Of People</div>
            <div class="col">Country</div>
            <div class="col">Details</div>
        </div>

        @foreach (var City in Model.Cities)
        {
            <div class="divChecker divHover tableBgColor row">

                <div class="col align-self-center">@City.CityName</div>
                <div class="col align-self-center">555</div>
                <div class="col align-self-center">@City.CountryId</div>
                <div class="col align-self-center">
                    <a asp-controller="Country" asp-action="Details" asp-route-id="@City.Id">
                        <input type="submit" class="btn btn-info" value="Details" />
                    </a>
                </div>

            </div>
        }
    </div>
}