08_People/Controllers/CountriesController.cs
using _08_People.Models.Entity;
using _08_People.Models.Services;
using _08_People.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace _08_People.Controllers
{
    public class CountriesController : Controller
    {
        private readonly ICountriesService _countriesService;
        public CountriesController(ICountriesService countriesService)
        {
            _countriesService = countriesService;
        }



        [HttpGet]
        public IActionResult Index(string search)
        {
            CountriesViewModel countries = new CountriesViewModel { Countries = _countriesService.Search(search) };  //Change to search?
            return View(countries);
        }

        [HttpGet]
        public ActionResult Create()
        {
            CreateCountryViewModel createCountry = new CreateCountryViewModel();
            return View(createCountry);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateCountryViewModel country)
        {
            if (ModelState.IsValid)
            {
                _countriesService.Add(country);
                return RedirectToAction(nameof(Index));     // Redirection to "Details" would be preferred
                //if throw new argumentexception needs to be added
            }
            return RedirectToAction(nameof(Create));
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            Country country = _countriesService.FindById(id);
            if (country == null) { RedirectToAction(nameof(Index)); }
            return View(country);
        }

        public ActionResult Edit(int id)    // Not implemented
        {
            //Person person = _peopleService.FindById(id);
            //if (person == null) { return RedirectToAction(nameof(Index)); }

            //CreatePersonViewModel editPerson = new CreatePersonViewModel()
            //{
            //    //Id = person.Id,   //Add and set Id in CreatePersonViewModel??
            //    FirstName = person.FirstName,
            //    LastName = person.LastName,
            //    PhoneNumber = person.PhoneNumber,
            //    InCity = person.InCity
            //};

            //ViewBag.Id = id;
            //return View(editPerson);
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit()    // Not implemented (int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

    }
}

08_People/Controllers/PeopleController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _08_People.Models.Entity;
using _08_People.Models.ViewModels;
using _08_People.Models.Services;
using _08_People.Models.Repos;

namespace _08_People.Controllers
{
    public class PeopleController : Controller
    {
        private readonly IPeopleService _peopleService;
        private readonly ICitiesService _citiesService;
        public PeopleController(IPeopleService ipeopleService, ICitiesService citiesService)
        {
            _peopleService = ipeopleService;
            _citiesService = citiesService;
        }



        [HttpGet]
        public ActionResult Index(string search)
        {
            PeopleViewModel people = new PeopleViewModel { Persons = _peopleService.Search(search) };
            return View(people);
        }


        [HttpGet]
        public ActionResult Create()
        {
            CreatePersonViewModel person = new CreatePersonViewModel();
            person.CityList = _citiesService.All();
            return View(person);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreatePersonViewModel person)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    _peopleService.Add(person);
                }
                catch (ArgumentException exception)
                {
                    ModelState.AddModelError("Person and City", exception.Message);
                    person.CityList = _citiesService.All();

                    return View(person);
                }
                return RedirectToAction(nameof(Index));     // Redirection to "Details" would be preferred
            }

            person.CityList = _citiesService.All();
            return RedirectToAction(nameof(Create));
        }


        [HttpGet]
        public ActionResult Details(int id)
        {
            Person person = _peopleService.FindById(id);
            if(person == null) { RedirectToAction(nameof(Index)); }
            //add if (person == null) redirect to index, or indicate in details view that person is gone (in case of deletion)
            return View(person);
        }


        public ActionResult Edit(int id)    // Not implemented
        {
            //Person person = _peopleService.FindById(id);
            //if (person == null) { return RedirectToAction(nameof(Index)); }

            //CreatePersonViewModel editPerson = new CreatePersonViewModel()
            //{
            //    //Id = person.Id,   //Add and set Id in CreatePersonViewModel??
            //    FirstName = person.FirstName,
            //    LastName = person.LastName,
            //    PhoneNumber = person.PhoneNumber,
            //    InCity = person.InCity
            //};

            //ViewBag.Id = id;
            //return View(editPerson);
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)    // Not implemented
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }


        public ActionResult Delete()
        {
            //might use for partial view, and load with "Are you sure?" question
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            Person person = _peopleService.FindById(id);
            if (person == null)
            {
                return RedirectToAction(nameof(Index));
            }
            _peopleService.Remove(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

08_People/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - _08_People</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">_08_People</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="People" asp-action="Index">People</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="People" asp-action="Create">Add Person</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Countries" asp-action="Index">Countries</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - _08_People - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

08_People/Views/Shared/_PeopleList.cshtml
@foreach (var Person in Model.Persons)
{
    @*<div class="container">*@
    //style="background-color:aliceblue"
        <div class="divChecker divHover tableBgColor row">

            <div class="col align-self-center">@Person.FirstName</div>
            <div class="col align-self-center">@Person.LastName</div>
            <div class="col align-self-center">@Person.City.CityName</div>
            <div class="col align-self-center">
                <a asp-controller="People" asp-action="Details" asp-route-id="@Person.Id">
                    <input type="submit" class="btn btn-info" value="Details" />
                </a>
            </div>

        </div>
    @*</div>*@
}